name: SIMLR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - django=2.2.5
  - openssl=1.1.1d
  - pip=19.3.1
  - python=3.7.5
  - pytz=2019.3
  - setuptools=42.0.2
  - sqlite=3.30.1
  - sqlparse=0.3.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
  - pip:
    - anndata==0.7rc1
    - cycler==0.10.0
    - decorator==4.4.1
    - h5py==2.10.0
    - importlib-metadata==1.3.0
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - llvmlite==0.30.0
    - matplotlib==3.0.3
    - more-itertools==8.0.2
    - natsort==6.2.0
    - networkx==2.4
    - numba==0.46.0
    - numexpr==2.7.0
    - numpy==1.18.0
    - pandas==0.25.3
    - patsy==0.5.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - scanpy==1.4.4.post1
    - scikit-learn==0.22
    - scipy==1.4.1
    - seaborn==0.9.0
    - six==1.13.0
    - statsmodels==0.11.0rc1
    - tables==3.6.1
    - tqdm==4.41.0
    - umap-learn==0.3.10
    - zipp==0.6.0

